name = input()
price = int(input())
weight = int(input())
cash = int(input())
print("=" * 16, "Чек", "=" * 16, sep="")
print(f"Товар: {name:>28}")
print("Цена:""{:>30}".format(f"{weight}кг * {price}руб/кг"))
print(f"Итого: {price * weight:>25}руб")
print(f"Внесено: {cash:>23}руб")
print(f"Сдача: {cash - price * weight:>25}руб")
print("=" * 35)
